### PR TITLE
Change const let logger

### PR DESCRIPTION
**Pull request by hammour**
changed "let" to "const" where required on lib>>logger.js

### CODE REVIEW

**Comment by alarner** [comment]
Looks good 👍 I discovered a new bug while testing this one. Not something you did, but a bug anyway. Maybe you can take a look at that next :) #73

**Comment by hammour** [comment]
Do you want me to fix it on the same branch? or shall i create a different one?

**Comment by alarner** [comment]
You can fix it here

**Comment by alarner** [comment]
👍

**Pull request merged**
